### ISSUE TITLE
Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by blimmer** [bep/homebrew-tap#1]
Recent versions of `brew` throw this error with this tap:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the bep/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/bep/homebrew-tap/Formula/s3deploy.rb:9
```

**Comment by bep** [comment]
This was fixed in https://github.com/goreleaser/goreleaser/releases/tag/v0.183.0 -- the latest s3deploy uses 0.176.0, but I will eventually get there ....

**Comment by blimmer** [comment]
No problem - I just wanted to make sure you were aware. This doesn't cause any problems at the moment. Thanks for all you do!
